---
title: EDH Library Maker Lab
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: maker-lab@eldoradolibrary.org
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
url: http://migue48.github.io
baseurl: "/edh-maker-lab-site"
cover: "/assets/cover.png"
logo: "/assets/logo.png"
twitter_username: jekyllrb
github_username: migue48
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- bundle
- vendor
